
compiler:
    - gcc
    - clang

language: objective-c

before_install:
 - brew update && brew outdated cmake || brew upgrade cmake
 - brew install libelf
script:
 - mkdir psp2
 - ./compile_travis.sh
 - ls -l psp2 psp2/host-osx psp2/inclide psp2/lib psp2/bin
 - grep error  error.txt

env:
 global:
  - TOP=$PWD
  - PSP2=$TOP/psp2
  - PSP2SDK=$PSP2
  - PATH=$PSP2/host-osx/bin:$PSP2/bin:$PATH




